apiVersion: rabc.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebind-pod
subjects:
    - kind: ServiceAccount
      name: userselfhost
      namespace: default
roleRef:
  apiGroup: rabc.authorization.k8s.io/v1
  kind: Role
  name: roll-pod

